kafka:
  topic: test
  bootstrap_servers: localhost:9092

hdfs:
  namenode: hdfs://localhost:9000

redis:
  host: localhost
  port: 6379

postgresql:
  host: localhost
  database: ml_pipeline
  user: postgres
  password: your_password

model:
  path: /usr/local/model

